### ISSUE TITLE
QuantLib 1.6

### ISSUE THREAD

**Issue by eddelbuettel** [rwinlib/quantlib#1]
Could you run another build for CRAN / win-builder, pretty-please?

Current sources at http://sourceforge.net/projects/quantlib/files/QuantLib/1.6/ and I had no issues whatsoever updating for Debian.

**Comment by jeroen** [comment]
Sure I'll have a look. This thing is huge though. Why doesn't it use `BH`?

**Comment by eddelbuettel** [comment]
I can't use BH on real computers where we use an external libquantlib -- as this could then introduce possiblu ABI difference between different Boost versions used by R (via BH) and QuantLib (via regular 'system' Boost). 

I have since updated the package on my PPA as well.  No issues.   This isn't urgent, but it would be really nice to have updated...

**Comment by eddelbuettel** [comment]
Thanks so much.  Email sent, wheels should be in motion,
